name: Deploy to Azure

on:
  push:
    branches: ["prod"]

  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # Checked out your repository
        uses: actions/checkout@v3

      - name: Setup Node # Installs NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies # Installs your app dependencies
        run: |
          cd rfd.client
          npm install

      - name: 'Login to Azure Subscription' # This is required for OIDC authentication to Azure
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B1491FF6B27842B6B6D96E4ADAE80A73 }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2D7E12C84FD8459ABE39A153D21426ED }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0BF94FA4435E40248537DE53E8140C29 }}
            
      - name: Build Next.js app
        run: |
          cd rfd.client
          npm run build
          mv .next/static .next/standalone/.next/static
          # mv public .next/standalone/public
          
      - name: Deploy
        shell: pwsh
        run: |
            cd rfd.client
            $ZIP_FILE_NAME = "./${FILE_NAME}.zip"
            zip $ZIP_FILE_NAME ./* .next -qr

            az webapp deploy `
                --resource-group $RESOURCE_GROUP_NAME `
                --name $WEB_APP_NAME `
                --src-path $ZIP_FILE_NAME `
                --slot staging `
                --type zip `
                --clean true 
        env:
            FILE_NAME: "rfd_nextjs_build"
            RESOURCE_GROUP_NAME: "rg-osku"
            WEB_APP_NAME: "app-osku-2"
